name: aula_3
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/caipirinha.jpg
    - assets/images/chicken-salad.png
    - assets/images/chicken-tender.png
    - assets/images/chicken-tortilla.png
    - assets/images/cold-noodles.png
    - assets/images/coxinhas.png
    - assets/images/fish-n-salsa.png
    - assets/images/hamburger-ink.png
    - assets/images/pamonha.png
    - assets/images/penne-au-sugo.png
    - assets/images/rice-n-beans.jpg
    - assets/images/shrimp-n-rice.png
    - assets/images/spagetti.png
    - assets/images/special-drink1.png
    - assets/images/special-drink2.png
    - assets/images/special-drink3.png
    - assets/images/special-drink4.png
    - assets/images/special-drink5.png
    - assets/images/special-drink6.png
    - assets/images/special-drink7.png
    - assets/images/steak-veggies.png
    - assets/images/steak.png
    - assets/images/tapioca-taco.jpg
    - assets/images/lasagna-bolognese.jpg
    - assets/images/visa.png

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
  # - family: Schyler
  #   fonts:
  #     - asset: assets/fonts/Schyler-Italic.ttf
  #       style: italic
  # - family: Trajan Pro
  #   fonts:
  #     - asset: assets/fonts/TrajanPro.ttf
  #     - asset: assets/fonts/TrajanPro_Bold.ttf
  #       weight: 700
